(defun test-multiple-values-bind ()
  (multiple-value-bind (firstname lastname age)
      (values "Alex" "Recker" 28)
    (format t "My name is ~s ~s and I am ~d years old." firstname lastname age)))

(defun test-hash ()
  (let ((hashy (make-hash-table)))
    (mapc #'(lambda (i)
	      (multiple-value-bind (k v)
		  (values (first i) (first (last i)))
		(setf (gethash k hashy) v)))
	  '((one 1) (two 2) (three 3)))
    (maphash #'(lambda (key val) (format t "k=~s,v=~s~%" key val)) hashy)))
